/**
 * Local email preview script.
 * Renders every email template to HTML files under tmp/ so you can open
 * them in a browser, send to test accounts, or paste into Litmus.
 *
 * Usage: npm run preview:emails
 *
 * Does NOT send any actual emails. No network calls. No env vars required.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { generateVerificationEmailHtml } from '../api/_email'
import { generateReminderEmailHtml } from '../api/_reminderEmail'

const OUT_DIR = resolve(__dirname, '..', 'tmp')
mkdirSync(OUT_DIR, { recursive: true })

const SAMPLE_BASE_URL = 'https://vininfo.cz'
const SAMPLE_UNSUBSCRIBE_URL = `${SAMPLE_BASE_URL}/api/email/unsubscribe?token=preview-token`

interface Variant {
	name: string
	html: string
}

const variants: Variant[] = [
	{
		name: 'verification',
		html: generateVerificationEmailHtml('482915')
	},
	{
		name: 'reminder-stk',
		html: generateReminderEmailHtml({
			vehicleName: 'Škoda Octavia (Firemní)',
			reminderType: 'Termín STK',
			reminderTypeRaw: 'stk',
			dueDate: '15. 6. 2026',
			note: 'Servisní knížka v přihrádce.',
			unsubscribeUrl: SAMPLE_UNSUBSCRIBE_URL,
			vehicleVin: 'WF0FXXWPCFHD05923',
			baseUrl: SAMPLE_BASE_URL
		})
	},
	{
		name: 'reminder-povinne-ruceni',
		html: generateReminderEmailHtml({
			vehicleName: 'VW Passat',
			reminderType: 'Povinné ručení',
			reminderTypeRaw: 'povinne_ruceni',
			dueDate: '3. 7. 2026',
			note: null,
			unsubscribeUrl: SAMPLE_UNSUBSCRIBE_URL,
			vehicleVin: 'WVWZZZ1KZDP015799',
			baseUrl: SAMPLE_BASE_URL
		})
	},
	{
		name: 'reminder-havarijni-pojisteni',
		html: generateReminderEmailHtml({
			vehicleName: 'Auto bílé',
			reminderType: 'Havarijní pojištění',
			reminderTypeRaw: 'havarijni_pojisteni',
			dueDate: '20. 8. 2026',
			note: 'Roční obnova.',
			unsubscribeUrl: SAMPLE_UNSUBSCRIBE_URL,
			vehicleVin: null,
			baseUrl: SAMPLE_BASE_URL
		})
	},
	{
		name: 'reminder-servis',
		html: generateReminderEmailHtml({
			vehicleName: 'Audi A4',
			reminderType: 'Servisní prohlídka',
			reminderTypeRaw: 'servis',
			dueDate: '10. 6. 2026',
			note: 'Olej, filtr, brzdy.',
			unsubscribeUrl: SAMPLE_UNSUBSCRIBE_URL,
			vehicleVin: null,
			baseUrl: SAMPLE_BASE_URL
		})
	},
	{
		name: 'reminder-dalnicni-znamka',
		html: generateReminderEmailHtml({
			vehicleName: 'Ford Focus',
			reminderType: 'Dálniční známka',
			reminderTypeRaw: 'dalnicni_znamka',
			dueDate: '31. 1. 2027',
			note: null,
			unsubscribeUrl: SAMPLE_UNSUBSCRIBE_URL,
			vehicleVin: null,
			baseUrl: SAMPLE_BASE_URL
		})
	},
	{
		name: 'reminder-jine',
		html: generateReminderEmailHtml({
			vehicleName: 'Camper',
			reminderType: 'Jiné',
			reminderTypeRaw: 'jine',
			dueDate: '1. 9. 2026',
			note: 'Revize plynové bomby.',
			unsubscribeUrl: SAMPLE_UNSUBSCRIBE_URL,
			vehicleVin: null,
			baseUrl: SAMPLE_BASE_URL
		})
	}
]

const indexLinks: string[] = []
for (const v of variants) {
	const filePath = resolve(OUT_DIR, `preview-${v.name}.html`)
	writeFileSync(filePath, v.html, 'utf-8')
	indexLinks.push(`<li><a href="preview-${v.name}.html">${v.name}</a></li>`)
	console.log(`  ✓ ${filePath}`)
}

const indexHtml = `<!DOCTYPE html>
<html lang="cs">
<head>
<meta charset="UTF-8">
<title>Email previews — VIN Info.cz</title>
<style>
	body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 640px; margin: 40px auto; padding: 0 16px; color: #0f172a; }
	h1 { font-size: 1.5rem; margin-bottom: 8px; }
	p { color: #64748b; }
	ul { padding-left: 20px; line-height: 2; }
	a { color: #2f7a3e; font-weight: 500; }
</style>
</head>
<body>
<h1>Email previews</h1>
<p>Generated by <code>npm run preview:emails</code>. Open each variant in your browser, then forward to your Gmail / Outlook / iCloud test accounts as needed.</p>
<ul>${indexLinks.join('\n')}</ul>
</body>
</html>`

const indexPath = resolve(OUT_DIR, 'index.html')
writeFileSync(indexPath, indexHtml, 'utf-8')

console.log(`\n  ✓ ${indexPath}\n`)
console.log(`Open file://${indexPath} in your browser.`)
