// Email sending utilities using Resend API

const getResendApiKey = (): string | null => {
	return process.env.RESEND_API_KEY || null
}

/**
 * From-address. Avoids "noreply" per Resend's deliverability guidance
 * (https://resend.com/docs/dashboard/emails/deliverability-insights —
 * no-reply addresses lower trust and engagement signals).
 */
const EMAIL_FROM = 'VIN Info.cz <vininfo@mail.vininfo.cz>'

/**
 * Reply-To target — a real monitored inbox so users who reply land
 * somewhere a human reads. Matches the contact address shown in the
 * site footer.
 *
 * Note: MX inbound for mail.vininfo.cz is configured for a future
 * webhook-based reply handler (Resend inbound requires a webhook —
 * https://resend.com/docs/dashboard/receiving/forward-emails). Until
 * that lands, replies go to the existing fixweb.cz mailbox.
 */
const EMAIL_REPLY_TO = 'vininfo@fixweb.cz'

/**
 * Absolute URL for the email logo. Must be reachable from any recipient's
 * client — Vercel serves /public assets at the apex domain. The PNG is
 * generated by `scripts/generate-email-logo.ts`.
 */
export const EMAIL_LOGO_URL = 'https://vininfo.cz/logo-email.png'

/**
 * Shared <style> block injected into the <head> of every email template.
 * Hosts the @media queries that inline styles can't express:
 *   - tighter padding/font-sizes below 480px (Gmail, Apple Mail respect)
 *   - dark-mode colour overrides (Apple Mail, iOS Mail, Outlook web/mobile,
 *     Gmail web respect prefers-color-scheme; Outlook desktop ignores
 *     and falls back to the inline light-mode styles — acceptable).
 *
 * Elements opt in by adding the appropriate class (email-body, email-surface,
 * email-tint, email-footer, email-text, email-text-muted, email-h2,
 * email-code, email-code-box, email-pad, email-border).
 */
export const EMAIL_HEAD_STYLES = `<style>
@media (max-width: 480px) {
	.email-pad { padding: 20px !important; }
	.email-pad-sm { padding: 16px !important; }
	.email-h2 { font-size: 18px !important; }
	.email-code { font-size: 28px !important; letter-spacing: 6px !important; }
}
@media (prefers-color-scheme: dark) {
	.email-body { background-color: #0f172a !important; }
	.email-surface { background-color: #1f2937 !important; }
	.email-tint { background-color: #1a3a22 !important; }
	.email-footer { background-color: #0f172a !important; }
	.email-text, .email-text strong, .email-h2 { color: #e5e7eb !important; }
	.email-text-muted, .email-text-muted a { color: #9ca3af !important; }
	.email-border { border-color: #374151 !important; }
}
</style>`

interface SendEmailParams {
	to: string
	subject: string
	html: string
	text?: string
	replyTo?: string
	headers?: Record<string, string>
}

// Helper to delay execution
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

export async function sendEmail(params: SendEmailParams): Promise<boolean> {
	const apiKey = getResendApiKey()
	if (!apiKey) {
		console.warn('RESEND_API_KEY is not configured, skipping email send')
		return false
	}

	const maxRetries = 3
	let lastError: string | null = null

	for (let attempt = 0; attempt < maxRetries; attempt++) {
		try {
			const response = await fetch('https://api.resend.com/emails', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Authorization': `Bearer ${apiKey}`
				},
				body: JSON.stringify({
					from: EMAIL_FROM,
					to: params.to,
					subject: params.subject,
					html: params.html,
					...(params.text ? { text: params.text } : {}),
					reply_to: params.replyTo ?? EMAIL_REPLY_TO,
					...(params.headers ? { headers: params.headers } : {})
				})
			})

			if (response.ok) {
				return true
			}

			const errorText = await response.text()
			lastError = `${response.status}: ${errorText}`

			// Retry on rate limit (429) with exponential backoff
			if (response.status === 429 && attempt < maxRetries - 1) {
				const backoffMs = Math.pow(2, attempt + 1) * 500 // 1s, 2s, 4s
				console.warn(`Resend rate limit hit, retrying in ${backoffMs}ms (attempt ${attempt + 1}/${maxRetries})`)
				await delay(backoffMs)
				continue
			}

			// Don't retry other errors
			console.error('Resend API error:', response.status, errorText)
			return false
		} catch (error) {
			lastError = error instanceof Error ? error.message : 'Unknown error'
			console.error('Failed to send email:', error)
			
			// Retry network errors with backoff
			if (attempt < maxRetries - 1) {
				const backoffMs = Math.pow(2, attempt + 1) * 500
				console.warn(`Email send failed, retrying in ${backoffMs}ms (attempt ${attempt + 1}/${maxRetries})`)
				await delay(backoffMs)
				continue
			}
			return false
		}
	}

	console.error('Email send failed after all retries:', lastError)
	return false
}

export function generateVerificationEmailHtml(code: string): string {
	const preheader = 'Dokončete registraci na VIN Info.cz — váš ověřovací kód uvnitř.'
	return `<!DOCTYPE html>
<html lang="cs">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="color-scheme" content="light dark">
	<meta name="supported-color-schemes" content="light dark">
	<meta name="format-detection" content="telephone=no,date=no,address=no,email=no">
	<meta name="x-apple-disable-message-reformatting">
	<title>Ověření emailu - VIN Info.cz</title>
	${EMAIL_HEAD_STYLES}
</head>
<body class="email-body" style="margin: 0; padding: 0; background-color: #f5f5f5; font-family: 'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333;">
	<div style="display:none!important;max-height:0;overflow:hidden;mso-hide:all;font-size:1px;line-height:1px;color:#f5f5f5;opacity:0;">${preheader}</div>
	<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" class="email-body" style="background-color: #f5f5f5;">
		<tr>
			<td align="center" style="padding: 20px;">
				<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width: 600px; width: 100%;">
					<tr>
						<td class="email-tint" style="background-color: #eaf4eb; padding: 25px 30px; border-radius: 8px 8px 0 0; text-align: center;">
							<a href="https://vininfo.cz" style="display: inline-block; text-decoration: none; color: inherit;">
								<img src="${EMAIL_LOGO_URL}" alt="" width="44" height="28" style="display: inline-block; vertical-align: middle; margin-right: 10px; border: 0;">
								<span class="email-text" style="display: inline-block; vertical-align: middle; font-size: 22px; color: #333; font-weight: 600;">VIN Info&#8203;.cz</span>
							</a>
						</td>
					</tr>
					<tr>
						<td class="email-surface email-pad email-border" style="background-color: #ffffff; padding: 30px; border-left: 1px solid #e9ecef; border-right: 1px solid #e9ecef;">
							<h2 class="email-h2" style="color: #333; margin: 0 0 16px; font-size: 20px;">Vítejte v Moje VINInfo!</h2>
							<p class="email-text" style="color: #555; margin: 0 0 16px;">Pro dokončení registrace zadejte následující ověřovací kód:</p>
							<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin: 25px 0;">
								<tr>
									<td class="email-tint" style="background-color: #eaf4eb; padding: 25px; border-radius: 8px; text-align: center;">
										<span class="email-code email-text" style="font-size: 36px; font-weight: bold; letter-spacing: 10px; color: #333;">${code}</span>
									</td>
								</tr>
							</table>
							<p class="email-text" style="color: #555; margin: 0 0 16px;">Kód je platný 24 hodin od odeslání.</p>
							<p class="email-text-muted" style="color: #888; font-size: 14px; margin: 25px 0 0;">Pokud jste si nevytvořili účet na VIN Info&#8203;.cz, tento email můžete ignorovat.</p>
						</td>
					</tr>
					<tr>
						<td class="email-footer email-border email-text-muted" style="background-color: #f8f9fa; padding: 20px; border: 1px solid #e9ecef; border-top: none; border-radius: 0 0 8px 8px; text-align: center; font-size: 12px; color: #888;">
							<p style="margin: 0;">Tento email byl odeslán ze služby <a href="https://vininfo.cz" style="color: #555; text-decoration: none;">VIN Info.cz</a></p>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</body>
</html>`
}

export function generateVerificationEmailText(code: string): string {
	return [
		'Vítejte v Moje VINInfo!',
		'',
		'Pro dokončení registrace zadejte následující ověřovací kód:',
		'',
		`    ${code}`,
		'',
		'Kód je platný 24 hodin od odeslání.',
		'',
		'Pokud jste si nevytvořili účet na VIN Info.cz, tento email můžete ignorovat.',
		'',
		'— VIN Info.cz (https://vininfo.cz)'
	].join('\n')
}

export async function sendVerificationEmail(email: string, code: string): Promise<boolean> {
	return sendEmail({
		to: email,
		subject: 'Ověřovací kód pro VINInfo',
		html: generateVerificationEmailHtml(code),
		text: generateVerificationEmailText(code)
	})
}
